### PR TITLE
update soon-to-be-deprecated model

### PR DESCRIPTION
**Pull request by C-Pro**
OpenAI has scheduled to deprecate model we are using `text-davinci-003` in early 2024.
https://openai.com/blog/gpt-4-api-general-availability

Changing it to the recommended replacement model 'gpt-3.5-turbo-instruct' and slightly tuning the prompt.

### CODE REVIEW

**Comment by egregors** [comment]
Lgtm

**Review by egregors — APPROVED** [review]

**Comment by C-Pro** [comment]
@egregors we need to update python-telegram-bot to new major version to update all vulnerable deps. It will break things

**Comment by egregors** [comment]
> @egregors we need to update python-telegram-bot to new major version to update all vulnerable deps. It will break things

It could be painful :/ Are we REALLY wanna do it? Is rust implementation still not ready?

**Comment by C-Pro** [comment]
> It could be painful :/ Are we REALLY wanna do it? Is rust implementation still not ready?

Of course it is. The question is the world ready for it?

**Pull request merged**
