### PR TITLE
dev: remove covid mode

### PR DESCRIPTION
**Pull request by AlexanderSutul**
https://github.com/vldc-hq/vldc-bot/pull/251
@getjump check plz. Maybe I missed something.

### CODE REVIEW

**Comment by AlexanderSutul** [comment]
#251  
@getjump check plz. Maybe I missed something.

**Comment by getjump** [comment]
@AlexanderSutul There are also dangling dependencies like "google-cloud-automl" which we don't need anymore, because it was used for mask detection. 
So removing it from `Pipfile`, updating `Pipfile.lock` via some kind of command. Also we can probably safely remove `vldc-bot/tf-model` folder. Also we don't need `serving` service anymore - so it is safe to remove from both `docker-compose.yml` and `docker-compose-dev.yml`, also don't forget to update `.vscode/tasks.json`.
That should be enough.

**Review by getjump — CHANGES_REQUESTED** [review]
Look at the comment

**Comment by C-Pro** [comment]
> @AlexanderSutul There are also dangling dependencies like "google-cloud-automl" which we don't need anymore, because it was used for mask detection. So removing it from `Pipfile`, updating `Pipfile.lock` via some kind of command. Also we can probably safely remove `vldc-bot/tf-model` folder. Also we don't need `serving` service anymore - so it is safe to remove from both `docker-compose.yml` and `docker-compose-dev.yml`, also don't forget to update `.vscode/tasks.json`. That should be enough.

This way our bot won't have AI! It lacks blockchain and bluetooth too. We need to fix it ASAP

**Comment by egregors** [comment]
rel #249

**Review by egregors — CHANGES_REQUESTED** [review]
As @getjump has mentioned above, these are still many things to do. Please, check original issue check-list.

**Comment by AlexanderSutul** [comment]
Updated.

**Comment by getjump** [comment]
@egregors Something went wrong with linter, can you check out?

**Review by getjump — APPROVED** [review]
LGTM

**Comment by egregors** [comment]
> @egregors Something went wrong with linter, can you check out?

I'll make the final check today. Did you fancy guys (@AlexanderSutul @getjump) try to build and run all this stuff on M1?

**Comment by AlexanderSutul** [comment]
> > @egregors Something went wrong with linter, can you check out?
> 
> I'll make the final check today. Did you fancy guys (@AlexanderSutul @getjump) try to build and run all this stuff on M1?

`make build` and `make up` works for me

**Comment by egregors** [comment]
@C-Pro is `regal-sun-144102-91ab4606de82.json` a part of covid mode?

**Comment by getjump** [comment]
> > @egregors Something went wrong with linter, can you check out?
> 
> I'll make the final check today. Did you fancy guys (@AlexanderSutul @getjump) try to build and run all this stuff on M1?

I have tried to run Dev Container, which runs just fine. Haven't tried `make build` and `make up` though. Also, i don't know maybe some flag or something runs virtualization layer idk, but it seems like it is native.

**Comment by C-Pro** [comment]
> @C-Pro is `regal-sun-144102-91ab4606de82.json` a part of covid mode? 

Yep. It is account keys.

**Review by egregors — APPROVED** [review]

**Comment by egregors** [comment]
Now, everything seems ok. I believe I can merge it now.

**Pull request merged**
