### PR TITLE
add pirozhkoviy skill

### PR DESCRIPTION
**Pull request by C-Pro**
Add a skill that once in 12 hours summarizes latest chat messages and tries to come up with an original poem about it.
It will be inspired enough for a poem if it has seen at least 10 text messages (not starting with '/') in last 6 hours.

### CODE REVIEW

**Comment by egregors** [comment]
@C-Pro is it summarizing the whole log? What about /roll noise?

**Comment by C-Pro** [comment]
> @C-Pro is it summarizing the whole log? What about /roll noise?

>  (not starting with '/') 

I think we should also filter out nyan.

**Comment by egregors** [comment]
> > @C-Pro is it summarizing the whole log? What about /roll noise?
> 
> > (not starting with '/')
> 
> I think we should also filter out nyan.

Yep, I'm generally about the same messages from Nyan

**Review by egregors — APPROVED** [review]

**Comment by egregors** [comment]
@C-Pro could you pls add some info into doc block in Readme? Just to know how to on_ oder off_ the mode

**Pull request merged**
